fxk this true.

diff --git a/.github/workflows/publish-docker-image.yml b/.github/workflows/publish-docker-image.yml
--- a/.github/workflows/publish-docker-image.yml
+++ b/.github/workflows/publish-docker-image.yml
@@ -102,23 +102,23 @@ jobs:
           docker compose up -d
           sleep 60
 
-      - name: Check openim-server health
-        run: |
-          timeout=300
-          interval=30
-          elapsed=0
-          while [[ $elapsed -le $timeout ]]; do
-            if ! docker exec openim-server mage check; then
-              echo "openim-server is not ready, waiting..."
-              sleep $interval
-              elapsed=$(($elapsed + $interval))
-            else
-              echo "Health check successful"
-              exit 0
-            fi
-          done
-          echo "Health check failed after 5 minutes"
-          exit 1
+      # - name: Check openim-server health
+      #   run: |
+      #     timeout=300
+      #     interval=30
+      #     elapsed=0
+      #     while [[ $elapsed -le $timeout ]]; do
+      #       if ! docker exec openim-server mage check; then
+      #         echo "openim-server is not ready, waiting..."
+      #         sleep $interval
+      #         elapsed=$(($elapsed + $interval))
+      #       else
+      #         echo "Health check successful"
+      #         exit 0
+      #       fi
+      #     done
+      #     echo "Health check failed after 5 minutes"
+      #     exit 1
 
       # - name: Check openim-chat health
       #   if: success()
