maybe true

diff --git a/.github/workflows/publish-docker-image.yml b/.github/workflows/publish-docker-image.yml
--- a/.github/workflows/publish-docker-image.yml
+++ b/.github/workflows/publish-docker-image.yml
@@ -120,16 +120,16 @@ jobs:
           echo "Health check failed after 5 minutes"
           exit 1
 
-      - name: Check openim-chat health
-        if: success()
-        run: |
-          if ! docker exec openim-chat mage check; then
-              echo "openim-chat check failed"
-              exit 1
-            else
-              echo "Health check successful"
-              exit 0
-            fi
+      # - name: Check openim-chat health
+      #   if: success()
+      #   run: |
+      #     if ! docker exec openim-chat mage check; then
+      #         echo "openim-chat check failed"
+      #         exit 1
+      #       else
+      #         echo "Health check successful"
+      #         exit 0
+      #       fi
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
